"""
Hand-authored 16x16 item/block sprites in the vanilla Minecraft idiom.

Each sprite is a 16-row x 16-col character grid. Characters index into PALETTE.
'.' is transparent. Authoring as text grids (rather than procedural noise) is
what lets these read as deliberate pixel art instead of coloured static.

Style rules being followed:
  - 3-4 shades per material: shadow / base / light / highlight
  - light source upper-left, so highlights sit top-left and shadow bottom-right
  - tools drawn on the diagonal, handle running bottom-left to top-right
  - silhouettes kept chunky; detail that does not read at 16px is noise

Run:  python3 tools/sprites.py           -> writes assets + contact sheet
"""
import os
import struct
import zlib

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "main", "resources", "assets", "lithic", "textures")
SHEET = os.path.join(os.path.dirname(__file__), "..", "build", "sprite-sheet.png")

PALETTE = {
    ".": None,
    # flint - cool dark grey
    "1": (0x2B, 0x2A, 0x2E), "2": (0x45, 0x44, 0x4A),
    "3": (0x5E, 0x5D, 0x66), "4": (0x7A, 0x79, 0x86),
    # wood / stick - oak brown
    "a": (0x4A, 0x3A, 0x21), "b": (0x6B, 0x53, 0x33),
    "c": (0x8A, 0x6D, 0x45), "d": (0xA8, 0x86, 0x56),
    # pale split wood - fresh cut face
    "e": (0x8A, 0x6F, 0x42), "f": (0xB2, 0x91, 0x5A),
    "g": (0xCD, 0xAA, 0x73), "h": (0xE0, 0xC4, 0x8E),
    # bark
    "i": (0x3E, 0x30, 0x1D), "j": (0x59, 0x45, 0x2B), "k": (0x6F, 0x58, 0x3A),
    # plant fibre - green
    "p": (0x4A, 0x5A, 0x28), "q": (0x66, 0x78, 0x3A),
    "r": (0x83, 0x96, 0x4F), "s": (0x9D, 0xB0, 0x66),
    # cordage - tan twine
    "t": (0x7A, 0x62, 0x38), "u": (0xA2, 0x86, 0x4F),
    "v": (0xC0, 0xA2, 0x68), "w": (0xD8, 0xBC, 0x85),
    # tinder - dry straw
    "x": (0x9A, 0x7B, 0x3C), "y": (0xC0, 0xA0, 0x55),
    "z": (0xDC, 0xBE, 0x74), "Z": (0xEF, 0xD7, 0x9A),
    # stone
    "A": (0x4F, 0x4F, 0x4F), "B": (0x6E, 0x6E, 0x6E),
    "C": (0x8A, 0x8A, 0x8A), "D": (0xA5, 0xA5, 0xA5),
    # fire
    "E": (0x8C, 0x2B, 0x0E), "F": (0xD2, 0x55, 0x1A),
    "G": (0xF0, 0x90, 0x2B), "H": (0xFF, 0xD3, 0x4D),
    # charcoal / ash
    "M": (0x1C, 0x1B, 0x1A), "N": (0x33, 0x31, 0x2F), "O": (0x55, 0x52, 0x4E),
}

ITEMS = {}
BLOCKS = {}

# --------------------------------------------------------------------- items --

ITEMS["flint_shard"] = """
................
................
................
.........1......
........134.....
.......13341....
......133441....
.....1233441....
.....122334.....
......12233.....
.......1221.....
........11......
................
................
................
................
"""

ITEMS["flint_blade"] = """
................
................
..............1.
.............14.
............134.
...........1234.
..........12234.
.........12234..
........12234...
.......12234....
......12234.....
.....12234......
....12234.......
....1223........
....122.........
.....1..........
"""

ITEMS["plant_fibre"] = """
................
................
.....p....p.....
....pq...pq.....
....qr...qr.....
...pqr..pqr..p..
...qrs..qrs.pq..
...qr...qr..qr..
..pqr..pqr..qr..
..qr...qr..pqr..
..qr...qr..qr...
..pq...pq..qr...
...p....p..pq...
............p...
................
................
"""

ITEMS["cordage"] = """
................
................
.....tttt.......
....tuvvut......
...tuvwwvut.....
...tuv..vut.....
...tuv..vut.....
...tuvwwvut.....
....tuvvut......
.....ttuv.......
.......tuv......
........tuv.....
.........tuv....
..........tu....
................
................
"""

ITEMS["bark"] = """
................
................
.......iiii.....
.....iijkkji....
....ijkkjjki....
...ijkkji.ii....
...ijkkji.......
..ijkkjji.......
..ijkkji........
..ijkkji........
..ijkjji........
..ijkji.........
..ijji..........
..iii...........
................
................
"""

ITEMS["tinder"] = """
................
................
................
....x..x...x....
...xy.xy..xy....
..xyzyxyz.xyz...
..xyzZzyzxyzy...
..xyzzZzyzyzy...
...xyzzzZzyzy...
...xyyzzzzyy....
....xyyzzyyx....
.....xxyyxx.....
......xxxx......
................
................
................
"""

ITEMS["rough_log"] = """
................
................
................
...iiiiiiiiii...
..ibbbjkjkjkji..
.ibcdcbkjkjkji..
.ibdedcjkjkjki..
.ibdedcjkjkjkj..
.ibcdcbkjkjkji..
..ibbbjkjkjkji..
...iiiiiiiiii...
................
................
................
................
................
"""

ITEMS["split_wood"] = """
................
................
...ijkeeeee.....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
..ijkefgfgfe....
...ijkeeeee.....
................
................
................
"""

ITEMS["hand_axe"] = """
................
..........111...
.........12334..
........122334..
........122334..
.......122334...
......t1223.....
.....tut12......
....tuvt.b......
....tut.ab......
.....t..bc......
.......abc......
......abc.......
.....abc........
.....ab.........
.....a..........
"""

ITEMS["crude_knife"] = """
................
................
............11..
...........1234.
..........12334.
.........12233..
........1223....
.......t122.....
......tut1......
.....tuvt.......
....tuvt........
....tut.........
....ta..........
...ab...........
...a............
................
"""

ITEMS["digging_stick"] = """
................
................
............11..
...........123..
..........1233..
..........122...
.........tut....
........tuvt....
........tut.....
.......abc......
......abc.......
.....abc........
.....abc........
....abc.........
....ab..........
....a...........
"""

ITEMS["fire_drill"] = """
................
..............a.
.............ab.
...........tabc.
..........tu.bc.
.........tu.abc.
........tu.abc..
.......tu.abc...
......tu.abc....
.....tu.abc.....
....tu.abc......
...tu.abc.......
...t.abc........
....abc.........
...abc..........
...ab...........
"""

# --------------------------------------------------------------------- blocks --

BLOCKS["knapping_site"] = """
BBBBBBBBBBBBBBBB
BCCCCBCCCCCBCCCB
BCDDCCCDDDCCCDCB
BCDDDCCDDDCCDDCB
BCCDDCCCDCCCDDCB
BCCCCC12CCCCCCCB
BCDCCC123CCCDDCB
BCDDCCC12CCCDDCB
BCCDCCCCCCCCCDCB
BCCCC12CCCDDCCCB
BCDDC123CCDDDCCB
BCDDCC12CCCDDCCB
BCCDCCCCCCCCDCCB
BCCCCCDDCCCCCCCB
BCCCCCDDCCCCCCCB
BBBBBBBBBBBBBBBB
"""

BLOCKS["chopping_block_top"] = """
iiiiiiiiiiiiiiii
ijjjjjjjjjjjjjji
ijbbbbbbbbbbbbji
ijbccccccccccbji
ijbcddddddddcbji
ijbcdeeeeeedcbji
ijbcdeffffedcbji
ijbcdefggfedcbji
ijbcdefggfedcbji
ijbcdeffffedcbji
ijbcdeeeeeedcbji
ijbcddddddddcbji
ijbccccccccccbji
ijbbbbbbbbbbbbji
ijjjjjjjjjjjjjji
iiiiiiiiiiiiiiii
"""

BLOCKS["chopping_block_side"] = """
iiiiiiiiiiiiiiii
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
iiiiiiiiiiiiiiii
"""

BLOCKS["fire_pit"] = """
................
................
..BC........CB..
.BCDB......BDCB.
.BCCB......BCCB.
..BB..aabb..BB..
......abba......
....abbaabba....
....baabbaab....
..BB.abbaab.BB..
.BCDB.aabb.BDCB.
.BCCB......BCCB.
..BC........CB..
................
................
................
"""

BLOCKS["fire_pit_lit"] = """
................
................
..BC...H....CB..
.BCDB.HGH..BDCB.
.BCCB.GHG..BCCB.
..BB.GFHFG..BB..
.....FGHGF......
....EFGHGFE.....
....EEFGFEE.....
..BB.EFGFE..BB..
.BCDB.MNM..BDCB.
.BCCB.MMM..BCCB.
..BC...M....CB..
................
................
................
"""


BLOCKS["chopping_block_top_loaded"] = """
iiiiiiiiiiiiiiii
ijjjjjjjjjjjjjji
ijbbbbbbbbbbbbji
ijbccccccccccbji
ijbcddddddddcbji
iiiiiiiiiiiiiiii
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
ijkjjkjjkjjkjjki
ijjkjjkjjkjjkjji
iiiiiiiiiiiiiiii
ijbcddddddddcbji
ijbccccccccccbji
ijbbbbbbbbbbbbji
ijjjjjjjjjjjjjji
iiiiiiiiiiiiiiii
"""

# Slatted rack: the gaps are transparent, so the block reads as a frame.
BLOCKS["drying_rack"] = """
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
"""

BLOCKS["drying_rack_occupied"] = """
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..qq..qq..qq....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..qq..qq..qq....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..qq..qq..qq....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
"""

BLOCKS["drying_rack_finished"] = """
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..zz..zz..zz....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..zz..zz..zz....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
..zz..zz..zz....
aaaaaaaaaaaaaaaa
abcbcbcbcbcbcbca
aaaaaaaaaaaaaaaa
................
"""


def _validate(name, grid):
    rows = [r for r in grid.strip("\n").split("\n")]
    if len(rows) != 16:
        raise ValueError(f"{name}: {len(rows)} rows, expected 16")
    for y, row in enumerate(rows):
        if len(row) != 16:
            raise ValueError(f"{name}: row {y} is {len(row)} wide, expected 16")
        for ch in row:
            if ch not in PALETTE:
                raise ValueError(f"{name}: row {y} uses undefined char {ch!r}")
    return rows


def _shade(rgb, factor):
    return tuple(max(0, min(255, int(v * factor))) for v in rgb)


def to_pixels(grid_rows, bevel=True):
    """Grid -> 16x16 RGBA. Optionally darkens the bottom edge of the silhouette."""
    px = [[(0, 0, 0, 0)] * 16 for _ in range(16)]
    for y, row in enumerate(grid_rows):
        for x, ch in enumerate(row):
            rgb = PALETTE[ch]
            if rgb is not None:
                px[y][x] = (rgb[0], rgb[1], rgb[2], 255)
    if bevel:
        # one-pixel darker lip along the bottom of each column, the cheap trick
        # vanilla uses to stop items looking flat
        for x in range(16):
            for y in range(15, -1, -1):
                if px[y][x][3]:
                    c = _shade(px[y][x][:3], 0.7)
                    px[y][x] = (c[0], c[1], c[2], 255)
                    break
    return px


def write_png(path, px, scale=1):
    w = h = 16 * scale
    raw = b""
    for y in range(h):
        raw += b"\x00"
        for x in range(w):
            raw += bytes(px[y // scale][x // scale])

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    blob = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(blob)


def contact_sheet(entries, path, scale=6, cols=5, pad=4):
    """One big magnified grid of every sprite, for eyeballing the whole set."""
    cell = 16 * scale + pad * 2
    rows = (len(entries) + cols - 1) // cols
    W, H = cols * cell, rows * cell
    canvas = [[(58, 58, 64, 255)] * W for _ in range(H)]
    for idx, (_name, px) in enumerate(entries):
        cx, cy = (idx % cols) * cell + pad, (idx // cols) * cell + pad
        for y in range(16 * scale):
            for x in range(16 * scale):
                p = px[y // scale][x // scale]
                if p[3]:
                    canvas[cy + y][cx + x] = p
                else:
                    # checkerboard so transparent areas are obvious
                    tone = 40 if ((x // scale + y // scale) // 2) % 2 == 0 else 48
                    canvas[cy + y][cx + x] = (tone, tone, tone, 255)

    raw = b""
    for y in range(H):
        raw += b"\x00" + b"".join(bytes(canvas[y][x]) for x in range(W))

    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", W, H, 8, 6, 0, 0, 0)
    blob = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(blob)


def main():
    sheet = []
    for name, grid in ITEMS.items():
        px = to_pixels(_validate(name, grid), bevel=True)
        write_png(os.path.join(OUT, "item", f"{name}.png"), px)
        sheet.append((name, px))
    for name, grid in BLOCKS.items():
        # blocks tile, so no bevel - it would show as a seam
        px = to_pixels(_validate(name, grid), bevel=False)
        write_png(os.path.join(OUT, "block", f"{name}.png"), px)
        sheet.append((name, px))

    contact_sheet(sheet, SHEET)
    print(f"{len(ITEMS)} item + {len(BLOCKS)} block sprites written")
    print("order: " + ", ".join(n for n, _ in sheet))
    print(f"contact sheet: {os.path.normpath(SHEET)}")


if __name__ == "__main__":
    main()
